### ISSUE TITLE
Compiler doesn't recognise the 'define' section when a comment preceeds it

### ISSUE THREAD

**Issue by seantiz** [Specy/rooc#21]
Salve!

I read through the docs but I am still unable to understand what the ROOCscript compiler expects after (or before) the `where` syntax

when i finish declaring constraints and move onto constants, i have these lines:

```
component_i >= min_instances(i) for i in 0..num_components
where
    // Memory footprint (MB) for each component type
    let mem_footprint = [2.5, 1.0, 3.0]
```

however the ROOC compiler throws an error at the very beginning of the `let mem_footprint` declaration:

```
Error at line 0:0 (l)
	[Unexpected token]   --> 17:5
   |
17 |     let mem_footprint = [2.5, 1.0, 3.0]
   |     ^---
   |
   = expected EOI or const_declaration
```

Any guidance is sincerely appreciated.

**Comment by seantiz** [comment]
All right I figured this out, it just needed simpler data constant names. I just saw the part of the documentation about compound variables. Unfortunately now I'm getting the same compiler error when trying to start off the `define` section to define the domain.

**Comment by seantiz** [comment]
> All right I figured this out, it just needed simpler data constant names. I just saw the part of the documentation about compound variables. Unfortunately now I'm getting the same compiler error when trying to start off the `define` section to define the domain.

Figured this out now as well. I included a comment before `define` and the compiler doesn't recognise the `define` decorator when there's a comment between it and the final constant value in `where`

**Comment by Specy** [comment]
Hello! Yeah the parser is a bit annoying sometimes, I should definitely improve it overall. 

I've managed to find all the places where comments break in blocks [here](https://rooc.specy.app/projects/share?project=N4IgbgpgTgzglgewHYgFwEYA0I4BM0gwAWAhlBCNlAK5IAucAthaiAPQBUAOkgMbIw6AAgBmcADYQYQgLxCA4gFEAKgH0AYgEkAMooDKACgCUPHuQDmcQdAPAeQh0KQlmqIQHIYARyh13me0dcKV4oOAAHBmQ3dwBhEnFeanESOgghOiJ072oydKgEBGEEESESJ2pGACNof0CHcLIXCDTYNwBtdvcS1SRK-yEABTDGOAZIADoAOUqaqABdeYCkRyFyOmooJBg3YaYxuEmZ6uhl1d4E8TcDPsYjWQA+ITsV1cd1zZXgOgBPcIg3FwQMc5kDMEIwAlqAChABZVJECbeXw3SoTSHiaFGAC+9SEuKQ2JMSB4-G2dBI9Bgtnqg00AAkEiI3MAMn8YUCQdAwRCoTD4ZkJnShGwhAAmfE8Ik8DhsSggGj0JgQABqVjgVUkaBECRgEGwzmYBAAqkhDRB8NhgjBQhEoihWPLQhBUhaAIJ0NDoADsAGYACwADgAbMH-b6AJwABmDgew1HCuFduA9Xr9QdD4ejsewYkkMDQ7SWIDJaXoBFGKwAHiK2FVyCQANYwHgwahVABWEF4wjoCFrAHcEFBm0I8ZwhAOwmkMlkhGTBFASHAqUIsuQhLK8TWHnIfjwB+v0mw6w3m+PRVOxulMukFxTV0e8ZJhD9ZEJ0FGeMExEhj6eXXPV4HBPIQfxXG850YBBgnETxeTCEhNSkNdoAgbcymkKZkCmCBzFSQ4IAAJRdcR5XCCIpELUAKP+NAo2wBB-gdHVxD1bFMBoyivUY5jtV1CAOK4ujUDFXiIBYgShJAWiWF9cTJLYwTOJk7iMCwEAmIktA6BoQT5mxIA)
I remember this issue popping up for me too, I don't remember why I hadn't fixed it, so hopefully there is a fix, else I'll add to the docs to not put comments there. 

I'll try to look at this whenever I get some time!

**Comment by seantiz** [comment]
> Hello! Yeah the parser is a bit annoying sometimes, I should definitely improve it overall.
> 
> I've managed to find all the places where comments break in blocks [here](https://rooc.specy.app/projects/share?project=N4IgbgpgTgzglgewHYgFwEYA0I4BM0gwAWAhlBCNlAK5IAucAthaiAPQBUAOkgMbIw6AAgBmcADYQYQgLxCA4gFEAKgH0AYgEkAMooDKACgCUPHuQDmcQdAPAeQh0KQlmqIQHIYARyh13me0dcKV4oOAAHBmQ3dwBhEnFeanESOgghOiJ072oydKgEBGEEESESJ2pGACNof0CHcLIXCDTYNwBtdvcS1SRK-yEABTDGOAZIADoAOUqaqABdeYCkRyFyOmooJBg3YaYxuEmZ6uhl1d4E8TcDPsYjWQA+ITsV1cd1zZXgOgBPcIg3FwQMc5kDMEIwAlqAChABZVJECbeXw3SoTSHiaFGAC+9SEuKQ2JMSB4-G2dBI9Bgtnqg00AAkEiI3MAMn8YUCQdAwRCoTD4ZkJnShGwhAAmfE8Ik8DhsSggGj0JgQABqVjgVUkaBECRgEGwzmYBAAqkhDRB8NhgjBQhEoihWPLQhBUhaAIJ0NDoADsAGYACwADgAbMH-b6AJwABmDgew1HCuFduA9Xr9QdD4ejsewYkkMDQ7SWIDJaXoBFGKwAHiK2FVyCQANYwHgwahVABWEF4wjoCFrAHcEFBm0I8ZwhAOwmkMlkhGTBFASHAqUIsuQhLK8TWHnIfjwB+v0mw6w3m+PRVOxulMukFxTV0e8ZJhD9ZEJ0FGeMExEhj6eXXPV4HBPIQfxXG850YBBgnETxeTCEhNSkNdoAgbcymkKZkCmCBzFSQ4IAAJRdcR5XCCIpELUAKP+NAo2wBB-gdHVxD1bFMBoyivUY5jtV1CAOK4ujUDFXiIBYgShJAWiWF9cTJLYwTOJk7iMCwEAmIktA6BoQT5mxIA) I remember this issue popping up for me too, I don't remember why I hadn't fixed it, so hopefully there is a fix, else I'll add to the docs to not put comments there.
> 
> I'll try to look at this whenever I get some time!
> 
> (I should also really work on the docs as they are a bit bad)

No worries, if you're open to contributions on the docs I am happy to look at where they could be more intuitive or seal some gaps.

In any case, thank you for making ROOC. It is super cool. I am still naive to many areas of maths, I was leaning heavily on Bayes for the last couple of years. I frankly did not know about coming up with optimisation models like the Diet Problem, and I'm enjoying building custom optimisation models so much that, frankly for the next month or so, I'm probably going to be guilty of building solutions in the search of a problem!

**Comment by Specy** [comment]
I'm glad you liked it! I've made it exactly to make it easier to build optimisation models for people who have few to no knowledge about linear programming, as I feel like it's an incredibly powerful tool.

And yes I'm open to contributions, the docs are here: 
https://github.com/Specy/rooc/tree/main/frontend/src/routes/docs/rooc

**Comment by Specy** [comment]
The issue with comments should be solved! let me know if it's fixed for you.

If you want to contribute to docs, look at #16

**Comment by seantiz** [comment]
> The issue with comments should be solved! let me know if it's fixed for you.
> 
> If you want to contribute to docs, look at #16

Yep, just to confirm I am not getting the comments error anymore either 👍
